export const USERS_DATA = [
    {
        user_id: 1,
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        password: 'password123',
        avatar: '/1.jpg',
        bio: "Hello, I'm John!",
        join_date: '2022-01-01',
        following_count: 85,
        follower_count: 73,
        post_count: 20,
    },
    {
        user_id: 2,
        username: 'jane_smith',
        name: 'Jane Smith',
        email: 'jane@example.com',
        password: 'example456',
        avatar: '/Breath of Thunder.jpg',
        bio: 'Nice to meet you!',
        join_date: '2022-02-15',
        following_count: 92,
        follower_count: 68,
        post_count: 15,
    },
    {
        user_id: 3,
        username: 'alexander',
        name: 'Alexander',
        email: 'alex@example.com',
        password: 'securePass',
        avatar: '/Gato Cholo.jpg',
        bio: 'Lorem ipsum dolor sit amet.',
        join_date: '2022-03-20',
        following_count: 63,
        follower_count: 89,
        post_count: 25,
    },
    {
        user_id: 4,
        username: 'emily_carter',
        name: 'Emily Carter',
        email: 'emily@example.com',
        password: 'pass1234',
        avatar: '/Gumball icon.jpg',
        bio: 'Hi there!',
        join_date: '2022-04-10',
        following_count: 77,
        follower_count: 54,
        post_count: 18,
    },
    {
        user_id: 5,
        username: 'michael_brown',
        name: 'Michael Brown',
        email: 'michael@example.com',
        password: 'mikepass',
        avatar: '/13.jpg',
        bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        join_date: '2022-05-05',
        following_count: 45,
        follower_count: 78,
        post_count: 22,
    },
    {
        user_id: 6,
        username: 'sophia_wilson',
        name: 'Sophia Wilson',
        email: 'sophia@example.com',
        password: 'pass456',
        avatar: '/7.jpg',
        bio: 'Welcome to my profile!',
        join_date: '2022-06-20',
        following_count: 68,
        follower_count: 91,
        post_count: 30,
    },
    {
        user_id: 7,
        username: 'daniel_jones',
        name: 'Daniel Jones',
        email: 'daniel@example.com',
        password: 'danielpass',
        avatar: '/2.jpg',
        bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        join_date: '2022-07-15',
        following_count: 82,
        follower_count: 63,
        post_count: 17,
    },
    {
        user_id: 8,
        username: 'olivia_anderson',
        name: 'Olivia Anderson',
        email: 'olivia@example.com',
        password: 'oliviapass',
        avatar: '/2.jpg',
        bio: 'Hello, world!',
        join_date: '2022-08-10',
        following_count: 71,
        follower_count: 76,
        post_count: 27,
    },
    {
        user_id: 9,
        username: 'william_thomas',
        name: 'William Thomas',
        email: 'william@example.com',
        password: 'will123',
        avatar: '/15.jpg',
        bio: 'Nice day!',
        join_date: '2022-09-05',
        following_count: 59,
        follower_count: 82,
        post_count: 16,
    },
    {
        user_id: 10,
        username: 'emma_martinez',
        name: 'Emma Martinez',
        email: 'emma@example.com',
        password: 'emmapass',
        avatar: '/2.jpg',
        bio: "Hi, I'm Emma!",
        join_date: '2022-10-01',
        following_count: 87,
        follower_count: 70,
        post_count: 21,
    },
];

export const POST_DATA = [
    {
        post_id: 1,
        user_id: 1,
        media_type: 'image',
        caption: 'Caption',
        post_date: '02/02/2024',
        media_url: '/1.png',
        like_count: 2000,
        comment_count: 200,
    },
    {
        post_id: 2,
        user_id: 1,
        media_type: 'image',
        caption: 'Caption',
        post_date: '02/02/2024',
        media_url: '/2.jpg',
        like_count: 23230,
        comment_count: 221,
    },
    {
        post_id: 3,
        user_id: 1,
        media_type: 'image',
        caption: 'Caption',
        post_date: '02/02/2024',
        media_url: '/3.jpg',
        like_count: 20,
        comment_count: 10,
    },
    {
        post_id: 4,
        user_id: 1,
        media_type: 'image',
        caption: 'Caption',
        post_date: '02/02/2024',
        media_url: '/7.jpg',
        like_count: 1342,
        comment_count: 210,
    },
    {
        post_id: 5,
        user_id: 1,
        media_type: 'image',
        caption: 'Caption',
        post_date: '02/02/2024',
        media_url: '/13.jpg',
        like_count: 273,
        comment_count: 90,
    },
    {
        post_id: 6,
        user_id: 1,
        media_type: 'image',
        caption: 'Caption',
        post_date: '02/02/2024',
        media_url: '/15.jpg',
        like_count: 100,
        comment_count: 200,
    },
];
