import type { Metadata } from 'next';
import React from 'react';
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthContextProvider } from '@/context/user';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Social App',
    description: 'Generated by Social app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    return (
        <html lang="en">
            <body className={inter.className} suppressHydrationWarning>
                <AuthContextProvider>{children}</AuthContextProvider>
            </body>
        </html>
    );
};

export default RootLayout;
