import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthContextProvider } from '@/context/user';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Social App',
    description: 'Generated by Social app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className} suppressHydrationWarning>
                <AuthContextProvider>{children}</AuthContextProvider>
            </body>
        </html>
    );
}
