export const POSTS_DATA = [
    {
        post_id: 1,
        user_id: 1,
        caption: 'Caption',
        post_date: new Date('2021-02-02T12:30:00.000Z'),
        media_url: '/1.png',
        like_count: 2000,
        comment_count: 200,
    },
    {
        post_id: 2,
        user_id: 1,
        caption:
            'Photography is the art of capturing light with a camera. It can be used to create images that tell stories, express emotions, or document reality. it can be fun, challenging, or rewarding. It can also be a hobby, a profession, or a passion',
        post_date: new Date('2024-03-21T10:15:00.000Z'),
        media_url: '/Gumball icon.jpg',
        like_count: 23230,
        comment_count: 221,
    },
    {
        post_id: 3,
        user_id: 1,
        caption: 'Caption',
        post_date: new Date('2024-03-23T10:15:00.000Z'),
        media_url: '/3.jpg',
        like_count: 20,
        comment_count: 10,
    },
    {
        post_id: 4,
        user_id: 1,
        caption: 'Caption',
        post_date: new Date('2024-03-23T21:15:00.000Z'),
        media_url: '/7.jpg',
        like_count: 1342,
        comment_count: 210,
    },
    {
        post_id: 5,
        user_id: 2,
        caption: 'Caption',
        post_date: new Date('2024-03-23T21:31:00.000Z'),
        media_url: '/13.jpg',
        like_count: 273,
        comment_count: 90,
    },
    {
        post_id: 6,
        user_id: 1,
        caption: 'Caption',
        post_date: new Date('2024-02-02T23:45:00.000Z'),
        media_url: '/15.jpg',
        like_count: 100,
        comment_count: 200,
    },
];
