export const USERS_DATA = [
    {
        user_id: 1,
        username: 'john_doe',
        name: 'John Doe',
        email: 'john@example.com',
        password: 'password123',
        avatar: '/1.jpg',
        bio: "Hello, I'm John!",
        join_date: new Date('2022-01-01T10:15:00.000Z'),
        following_count: 85,
        follower_count: 73,
        post_count: 20,
    },
    {
        user_id: 2,
        username: 'jane_smith',
        name: 'Jane Smith',
        email: 'jane@example.com',
        password: 'example456',
        avatar: '/16.jpg',
        bio: 'Nice to meet you!',
        join_date: new Date('2022-02-15T09:45:00.000Z'),
        following_count: 92,
        follower_count: 68,
        post_count: 15,
    },
    {
        user_id: 3,
        username: 'alexander',
        name: 'Alexander',
        email: 'alex@example.com',
        password: 'securePass',
        avatar: '/Gato Cholo.jpg',
        bio: 'Lorem ipsum dolor sit amet.',
        join_date: new Date('2022-03-20T14:30:00.000Z'),
        following_count: 63,
        follower_count: 89,
        post_count: 25,
    },
    {
        user_id: 4,
        username: 'emily_carter',
        name: 'Emily Carter',
        email: 'emily@example.com',
        password: 'pass1234',
        avatar: '/Gumball icon.jpg',
        bio: 'Hi there!',
        join_date: new Date('2022-04-10T08:20:00.000Z'),
        following_count: 77,
        follower_count: 54,
        post_count: 18,
    },
    {
        user_id: 5,
        username: 'michael_brown',
        name: 'Michael Brown',
        email: 'michael@example.com',
        password: 'mikepass',
        avatar: '/13.jpg',
        bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        join_date: new Date('2022-05-05T12:00:00.000Z'),
        following_count: 45,
        follower_count: 78,
        post_count: 22,
    },
    {
        user_id: 6,
        username: 'sophia_wilson',
        name: 'Sophia Wilson',
        email: 'sophia@example.com',
        password: 'pass456',
        avatar: '/7.jpg',
        bio: 'Welcome to my profile!',
        join_date: new Date('2022-06-20T17:45:00.000Z'),
        following_count: 68,
        follower_count: 91,
        post_count: 30,
    },
    {
        user_id: 7,
        username: 'daniel_jones',
        name: 'Daniel Jones',
        email: 'daniel@example.com',
        password: 'danielpass',
        avatar: '/2.jpg',
        bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        join_date: new Date('2022-07-15T13:10:00.000Z'),
        following_count: 82,
        follower_count: 63,
        post_count: 17,
    },
    {
        user_id: 8,
        username: 'olivia_anderson',
        name: 'Olivia Anderson',
        email: 'olivia@example.com',
        password: 'oliviapass',
        avatar: '/2.jpg',
        bio: 'Hello, world!',
        join_date: new Date('2022-08-10T20:25:00.000Z'),
        following_count: 71,
        follower_count: 76,
        post_count: 27,
    },
    {
        user_id: 9,
        username: 'william_thomas',
        name: 'William Thomas',
        email: 'william@example.com',
        password: 'will123',
        avatar: '/15.jpg',
        bio: 'Nice day!',
        join_date: new Date('2022-09-05T16:55:00.000Z'),
        following_count: 59,
        follower_count: 82,
        post_count: 16,
    },
    {
        user_id: 10,
        username: 'emma_martinez',
        name: 'Emma Martinez',
        email: 'emma@example.com',
        password: 'emmapass',
        avatar: '/2.jpg',
        bio: "Hi, I'm Emma!",
        join_date: new Date('2022-10-01T18:40:00.000Z'),
        following_count: 87,
        follower_count: 70,
        post_count: 21,
    },
];
